version: '3.6'
services:

  mongo:
      image: mongo:4.4.22
      container_name: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
        MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
        MONGO_INITDB_DATABASE: hotelsdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
        ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
        ME_CONFIG_MONGODB_URL: $MONGO_URL

  hotels:
    container_name: diplom
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=$HTTP_PORT
    ports:
      - 80:$HTTP_PORT
    depends_on:
      - mongo